Add read and write interceptors
realtime-sanitizer/llvm-project pull request #26
Opened 2024-06-04 01:45 UTC by cjappl

Note the base branch of this is RadsanBackend - Accepting and merging this PR will put it in the main code review branch.

Add read/write interceptors. Introduce a fixture that opens and closes a file, and allows access via an fd and a FILE*.

Also fix some inconsistent naming for our lambda, we were about 50/50 `func`/`Func`. I still do not know which is appropriate for lambdas, as they are a variable (`variable_case`) which is a function (`FunctionCase`)

2024-06-04 09:34 UTC, davidtrevelyan requested changes
Other than one very minor nit, LGTM. We should probably mirror this change across to the `radsan` branch, right? And, until `RadsanBackend` is merged upstream, probably wise to do it in `upstream-radsan-v0` as well - what do you think?

Maybe you could do the cherry-picking and parent-project MR for `realtime-sanitizer/radsan`, and then I can kick off the docker release once it's merged?

Many thanks as always for your efforts on this!

2024-06-04 09:34 UTC, davidtrevelyan commented on compiler-rt/lib/rtsan/tests/rtsan_test_interceptors.cpp
> +TEST_F(RtsanOpenedFileTest, readDiesWhenRealtime) {
Very minor nit: test function names introduced here and below are lowerCamelCase, but UpperCamelCase above!

2024-06-11 15:22 UTC, davidtrevelyan approved these changes

2024-09-21 18:27 UTC, cjappl commented
This has been integrated upstream

2024-09-21 18:27 UTC, closed without merging